### PR TITLE
VIDCS-706 Updated AudioDeviceNotifications sample to 2.25.3

### PR DESCRIPTION
**Pull request by sergioturgil-vonage**
Update AudioDeviceNotifications sample to 2.25.3 from the previous beta version of MMAudioDevice.

The sample can be tested by connecting/disconnecting audio devices or changing windows OS level default settings.

### CODE REVIEW

**Comment by goncalocostamendes** [comment]
@sergioturgil-vonage build is failing

**Comment by sergioturgil-vonage** [comment]
> This is the same app that solves the https://jira.vonage.com/browse/VIDCS-505 ticket, right? Seems the client still found an issue. You and Yukari synced offline. Is the issue solved?

Yes. I synced with Yukari and provided an update on customer test app that works correctly. Let's see what the customer says.
This sample is the normalized way of using the new custom audio device for advanced audio management.

**Comment by sergioturgil-vonage** [comment]
> @sergioturgil-vonage build is failing

Yes. It builds and works fine when cloning the repo. I don't know what the problem with this CI is but I suppose at one point we should move it to start using our own action runners. I'll ask for this in our team sync.

**Review by goncalocostamendes — APPROVED** [review]
LGTM! Approving it since Yukari also tested it out and everything is working well. GoInStore is going to test it out now. We can wait for their feedback to merge it, but I will leave that decision to you @sergioturgil-vonage

**Comment by IGitGotIt** [comment]
@sergioturgil-vonage do we have any developer guide which schematically shows the life cycle  ?

**Review by IGitGotIt — APPROVED** [review]
+1

**Pull request merged**
