### PR TITLE
VIDCS-910 - Update windows samples to 2.25.1

### PR DESCRIPTION
**Pull request by sergioturgil-vonage**
Apart from updating all samples to 2.25.1 (BasicVideoChat was already updated) I've removed x86 compilation from 3 of the samples since the SDK is no longer compatible with that arch.
I've also modified a bit the code in a couple of samples to make sure that if customers decide to use .NetCore audio works correctly (audio device enumeration is only available after publisher has been created)

### CODE REVIEW

**Comment by v-kpheng** [comment]
@sergioturgil-vonage, looks good! 💪 

That said, is it possible to have the package version number to be used by all the sample apps in a single file?  That way, when we a new version of the Windows SDK is published, we only need to edit one file 🤞

Please advise.  Thanks! 🙏

**Comment by sergioturgil-vonage** [comment]
> @sergioturgil-vonage, looks good! 💪
> 
> That said, is it possible to have the package version number to be used by all the sample apps in a single file? That way, when we a new version of the Windows SDK is published, we only need to edit one file 🤞
> 
> Please advise. Thanks! 🙏

Yes, I think that should be possible.
There are two ways to set the dependencies. Via packages.config file which would be the easiest way to share one file but it's also the legacy way, so not recommended. Via a separate properties file included from all projects.
I'm going to take a look at the second way.

**Comment by sergioturgil-vonage** [comment]
> > @sergioturgil-vonage, looks good! 💪
> > That said, is it possible to have the package version number to be used by all the sample apps in a single file? That way, when we a new version of the Windows SDK is published, we only need to edit one file 🤞
> > Please advise. Thanks! 🙏
> 
> Yes, I think that should be possible. There are two ways to set the dependencies. Via packages.config file which would be the easiest way to share one file but it's also the legacy way, so not recommended. Via a separate properties file included from all projects. I'm going to take a look at the second way.

Ok, so I did the requested changes and the result is that this PR now changes a lot of files. It's much more simple than it looks. Let me explain:

Dependencies were being added as a direct link to the packages in a local folder which was causing the repo to contain a lot of unnecesary very large files. It was also the cause of several problems. FOr example BasicVideoChat was updated to version 2.25.1 but internally it was referencing the local package for 2.24.0.
Now dependencies are downloaded from internet, as it should be.
Of course removing all those unnecesary files causes this PR to look huge but it's not.
In fact all removed files inside packages/* folders can be ignored in the review.

**Review by v-kpheng — APPROVED** [review]
LGTM! 💪 🚀

**Comment by tnas32** [comment]
Everything works very well !

**Pull request merged**
