### PR TITLE
VIDCS-2643 Fixed a couple of problems in WinForms sample

### PR DESCRIPTION
**Pull request by sergioturgil-vonage**

### CODE REVIEW

**Review by juliobecerragomez — COMMENTED** [review]
+1

**Review by juliobecerragomez — APPROVED** [review]

**Review by goncalocostamendes — APPROVED** [review]
+1

**Review by goncalocostamendes — CHANGES_REQUESTED** [review]
There are some more issues on the samples

`"C:\Users\travis\build\opentok\opentok-windows-sdk-samples\Samples.sln" (default target) (1) ->
"C:\Users\travis\build\opentok\opentok-windows-sdk-samples\ScreenSharing\ScreenSharing.csproj" (default target) (10) ->
(MarkupCompilePass1 target) -> 
  C:\Users\travis\build\opentok\opentok-windows-sdk-samples\ScreenSharing\MainWindow.xaml(13,6): error MC3074: The tag 'VideoRenderer' does not exist in XML namespace 'clr-namespace:OpenTok;assembly=WPFVideoRenderer'. Line 13 Position 6. [C:\Users\travis\build\opentok\opentok-windows-sdk-samples\ScreenSharing\ScreenSharing.csproj]
"C:\Users\travis\build\opentok\opentok-windows-sdk-samples\Samples.sln" (default target) (1) ->
"C:\Users\travis\build\opentok\opentok-windows-sdk-samples\SimpleMultiparty\SimpleMultiparty.csproj" (default target) (11) ->
  C:\Users\travis\build\opentok\opentok-windows-sdk-samples\SimpleMultiparty\MainWindow.xaml(13,6): error MC3074: The tag 'VideoRenderer' does not exist in XML namespace 'clr-namespace:OpenTok;assembly=WPFVideoRenderer'. Line 13 Position 6. [C:\Users\travis\build\opentok\opentok-windows-sdk-samples\SimpleMultiparty\SimpleMultiparty.csproj]
"C:\Users\travis\build\opentok\opentok-windows-sdk-samples\Samples.sln" (default target) (1) ->
"C:\Users\travis\build\opentok\opentok-windows-sdk-samples\Transformers\Transformers.csproj" (default target) (12) ->
  C:\Users\travis\build\opentok\opentok-windows-sdk-samples\Transformers\MainWindow.xaml(11,10): error MC3074: The tag 'VideoRenderer' does not exist in XML namespace 'clr-namespace:OpenTok;assembly=WPFVideoRenderer'. Line 11 Position 10. [C:\Users\travis\build\opentok\opentok-windows-sdk-samples\Transformers\Transformers.csproj]`

**Comment by sergioturgil-vonage** [comment]
> There are some more issues on the samples
> 
> `"C:\Users\travis\build\opentok\opentok-windows-sdk-samples\Samples.sln" (default target) (1) -> "C:\Users\travis\build\opentok\opentok-windows-sdk-samples\ScreenSharing\ScreenSharing.csproj" (default target) (10) -> (MarkupCompilePass1 target) -> C:\Users\travis\build\opentok\opentok-windows-sdk-samples\ScreenSharing\MainWindow.xaml(13,6): error MC3074: The tag 'VideoRenderer' does not exist in XML namespace 'clr-namespace:OpenTok;assembly=WPFVideoRenderer'. Line 13 Position 6. [C:\Users\travis\build\opentok\opentok-windows-sdk-samples\ScreenSharing\ScreenSharing.csproj] "C:\Users\travis\build\opentok\opentok-windows-sdk-samples\Samples.sln" (default target) (1) -> "C:\Users\travis\build\opentok\opentok-windows-sdk-samples\SimpleMultiparty\SimpleMultiparty.csproj" (default target) (11) -> C:\Users\travis\build\opentok\opentok-windows-sdk-samples\SimpleMultiparty\MainWindow.xaml(13,6): error MC3074: The tag 'VideoRenderer' does not exist in XML namespace 'clr-namespace:OpenTok;assembly=WPFVideoRenderer'. Line 13 Position 6. [C:\Users\travis\build\opentok\opentok-windows-sdk-samples\SimpleMultiparty\SimpleMultiparty.csproj] "C:\Users\travis\build\opentok\opentok-windows-sdk-samples\Samples.sln" (default target) (1) -> "C:\Users\travis\build\opentok\opentok-windows-sdk-samples\Transformers\Transformers.csproj" (default target) (12) -> C:\Users\travis\build\opentok\opentok-windows-sdk-samples\Transformers\MainWindow.xaml(11,10): error MC3074: The tag 'VideoRenderer' does not exist in XML namespace 'clr-namespace:OpenTok;assembly=WPFVideoRenderer'. Line 11 Position 10. [C:\Users\travis\build\opentok\opentok-windows-sdk-samples\Transformers\Transformers.csproj]`

mmm... It seems that the CI constantly fails because of this. Weirdly enough it's not a problem that happens when you download and build the samples locally in VS. Neither has it been reported before for any user doing the same operation.
So it's possible it's just a problem in how the CI is being run (maybe some dependencies missing in the computer???).
Another possibility lies in the difference between building through VS or directly through MSBuild.

I'll open a ticket to take a look at this but since it's not related to the fix in this ticket I'll merge these changes so Douglas can get the fix before starting looking at the samples CI problem.

**Pull request merged**
